version: 2

# Defining default values for all jobs
defaults: &defaults
  docker:
    - image: circleci/node:latest

jobs:
  setup_dx:
    # This command runs the preparation steps needed for the CI workflow:
    #
    # - Installation of the Salesforce CLI using npm
    # - Authentication of the DevHub
    # - Creation of a scratch org
    #
    # While a scratch org isn't needed in all steps it's still part of the process. The reason for this is
    # that we need to store the sfdx configuration files for it in the workspace, so that data can be shared
    # across different workflow steps.
    #
    # Keep it simple!
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Salesforce DX
          command: . build/install_sfdx.sh
      
      - run:
          name: Authenticate DevHub
          command: . build/authenticate_devhub.sh
              
      - run:
          name: Define CI Org
          # We define the to be used CI org. Based on the branch we either create a new scratch org
          # or we use a project variable to authenticate a UAT or full-copy sandbox as target org.
          #
          # You can get the sfdxurl via sfdx force:org:display -u yourOrg --json --verbose from your local machine.
          command: |
              echo $SFDX_AUTH_PACKAGING > ~/auth.url
              node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -s -a packagingorg -f ~/auth.url
              . build/create_scratch_org.sh

      - persist_to_workspace:
          # This is an important step. If we don't store the project data (cloned GitHub source and node_modules from the CLI installation)
          # we'd have to re-run installation for every workflow step.
          #
          # Also this step is crucial as we use it to share sfdx config parameters between steps.
          root: ~/
          paths:
              - .sfdx/*
              - project/*
  
  deploy_source:
  # This deploys the source to the ci scratch org.
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Push Source
          command: . build/deploy_source.sh
             
  
  create_and_test_package:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Create and install package
          command: |
            if [[ $SFDX_TEST_PACKAGING == "true" ]]; then
              scripts/packagingDeployment.sh
            fi
          no_output_timeout: 15m

  run_apex_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Apex Tests
          command: . build/run_apex_test.sh
  
  cleanup_scratch_org:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Clean Up
          command: . build/delete_scratch_org.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_dx
      - deploy_source:
          requires:
            - setup_dx
          filters:
            branches:
              ignore: master
      - create_and_test_package:
          requires:
            - setup_dx
          filters:
            branches:
              only: master
      - run_apex_tests:
          requires:
            - deploy_source
          filters:
            branches:
              ignore: master
      - cleanup_scratch_org:
          requires:
            - setup_dx
            - deploy_source
            - create_and_test_package
            - run_apex_tests
